services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8081:80"
    volumes:
      - ./frontend:/usr/share/caddy/
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - postgres
      - rabbitmq
    
  postgres:
     image: postgres:18-alpine
     environment:
       POSTGRES_DB: postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: password
     ports:
       - "5432:5432"
     volumes:
       - ./.db:/var/lib/postgresql
       
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"  # Management UI

  email-service:
    build: ./email-service
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - rabbitmq
    #deploy:
    #   replicas: 2
  fulfilment-service:
    build: ./fulfilment-service
    environment:
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      - rabbitmq
 